############################
## CHANGE THESE
############################

baseURL: "https://Mewzael/mewzael.github.io"
title: mewzael.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
