############################
## CHANGE THESE
############################

baseURL: "https://mewzael.github.io"
title: "Qubt Theme"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true

markup:
  goldmark:
    renderHooks:
      image:
        enableDefault: true
